# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('address_1', models.TextField(blank=True)),
                ('address_2', models.TextField(blank=True)),
                ('act_name', models.TextField(blank=True)),
            ],
        ),
    ]
