# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='lat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='lon',
            field=models.TextField(blank=True),
        ),
    ]
