# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import heritage.models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_auto_20161028_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.HeritageObject')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=heritage.models.object_directory_path),
        ),
    ]
