# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:25
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('heritage', '0004_auto_20161028_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
